# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0634314410d0bd6cd30e7819e12803a49c065e949f0eab4032af8e2409e2a4c4cd637abc53487628cd1125714f7426be61f35bd8afb3abc0a4760fbfead52698

test:
  secret_key_base: 8a8890be5a27b68cdd15716fdac9743f047b9bea17306fe15b794bd14f97a5491d7b27120b81170ba33aac3424f77b49455836728ffa97905cf892d1f457448e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
